spring:
  application:
    name: gatewat-loadbalancer-demo
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      health-check:
        interval: 5s
    gateway:
      routes:
        - id: my-service
          uri: lb://my-service
          predicates:
            - Path=/service/**
          filters:
            - RewritePath=/service(?<segment>/?.*), $\{segment}
        - id: app-service
          uri: lb://app-service
          predicates:
            - Path=/app/**
          filters:
            - RewritePath=/app(?<segment>/?.*), $\{segment}
      loadbalancer:
        use404: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
        max-header-size: 10KB
  http:
    log-request-details: true
application:
  load-balancer-clients:
    my-service:
      - host: 127.0.0.1
        port: 9001
        secure: false
      - host: 127.0.0.1
        port: 9011
        secure: false
    app-service:
      - host: 127.0.0.1
        port: 9002
        secure: false
      - host: 127.0.0.1
        port: 9022
        secure: false
logging:
  level:
    org.springframework.cloud.gateway.filter: trace
    org.springframework.web.reactive.function.client: trace

